### ISSUE TITLE
Sesión Exploratoria-Error2: Jugador bloqueado en una pared

### ISSUE THREAD

**Issue by PabloFernandezAl01** [Proyectos1-FDI-UCM/c1920-Grupo07#3]
Descripción
Si el jugador se desliza por la pared adjuntada en la imagen, y mantiene la Tecla “a”, es decir, la correspondiente a la pared en la que te estas “deslizando”, se queda bloqueado hasta que el jugador deje de presionar esa tecla o invierta la gravedad.
Pasos
1.      Salta hacia la pared de la imagen
2.      Mantén “a” cuando estas pegado a ella.
3.      Puede que no se produzca a la primera , ir al paso 1 en este caso.
Video:
https://www.youtube.com/watch?v=iiGs1VTQhr4

**Comment by ghost** [comment]
Encontré un caso muy similar por lo que en vez de crear un nuevo issue os adjunto un video donde se aprecia: https://www.youtube.com/watch?v=oF8fEdBNo98&feature=youtu.be
