### ISSUE TITLE
Sesión Explorativa - Error 7 - Animación del personaje bugeada

### ISSUE THREAD

**Issue by alvaga31** [Proyectos1-FDI-UCM/c1920-Grupo07#8]
Descripción
En la parte del mapa que van los cosas muy rápido, más especificamente en la zona de la plataforma movible horizontal. Si el jugador se coloca en el borde para ir a la plataforma, y esta le da, el personaje se queda bugeado sin poder saltar.

Pasos
1.	Ir a la parte del mapa anteriormente mencionada
2.	Colocarse justo en el borde antes de llegar a la platofarma
3.	Dejar que la plataforma choque con el jugador

Captura de pantalla o vídeo

![Error 7](https://user-images.githubusercontent.com/63009531/82737940-93b20880-9d34-11ea-871e-e87c0abbc4ab.png)

**Comment by iquintasALT** [comment]
En mi caso he conseguido que el jugador se quede en el mismo estado mientras probaba el [Error2](https://github.com/Proyectos1-FDI-UCM/c1920-Grupo07/issues/3).
Añado un vídeo de como ocurrió [https://youtu.be/WZM63veJe3I](https://youtu.be/WZM63veJe3I)
