### ISSUE TITLE
Sesión Explorativa - Error 8 - Ventana de menú/pausa

### ISSUE THREAD

**Issue by alvaga31** [Proyectos1-FDI-UCM/c1920-Grupo07#9]
Descripción
Cuando pulsas “esc” y se abre la pestaña de menú/pausa, se puede seguir usando tanto el poder del tiempo como el poder de la gravedad. Además de que si usas el poder del tiempo en esta situación, no se gasta la barra entera como debería pasar, solo se gasta una parte de esta.

Pasos
1.	Pulsar esc
2.	Pulsar shift izquierdo o click derecho para gastar los poderes

Captura de pantalla o vídeo

https://www.youtube.com/watch?v=Ffd3nXwfZq0

**Comment by ghost** [comment]
Encontré el mismo fallo y añadir que los efectos de los poderes ocurren tras cerrar el menú.
